-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.curso
(
    id_curso integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_instituicao integer,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT curso_pkey PRIMARY KEY (id_curso)
);

CREATE TABLE IF NOT EXISTS public.disciplina
(
    id_disciplina integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_curso integer NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    carga_horaria integer NOT NULL,
    CONSTRAINT disciplina_pkey PRIMARY KEY (id_disciplina)
);

CREATE TABLE IF NOT EXISTS public.estatisticas_desempenho
(
    id_estatistica integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    media_global numeric(4, 2) NOT NULL,
    semestre integer NOT NULL,
    reprovacoes integer NOT NULL,
    ch_semestre integer NOT NULL,
    turmas integer NOT NULL,
    maior_influencia_evasao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    semestre_saida integer,
    id_estudante integer NOT NULL,
    risco integer,
    CONSTRAINT estatisticas_desempenho_pkey PRIMARY KEY (id_estatistica)
);

CREATE TABLE IF NOT EXISTS public.estudante
(
    matricula integer NOT NULL,
    id_instituicao integer,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_ingresso date NOT NULL,
    CONSTRAINT estudante_pkey PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS public.estudante_grupo
(
    id_grupo integer NOT NULL,
    id_estudante integer NOT NULL,
    CONSTRAINT id_estudante_grupo PRIMARY KEY (id_estudante, id_grupo)
);

CREATE TABLE IF NOT EXISTS public.estudante_turma
(
    id_turma integer NOT NULL,
    id_estudante integer NOT NULL,
    CONSTRAINT id_estudante_turma PRIMARY KEY (id_estudante, id_turma)
);

CREATE TABLE IF NOT EXISTS public.grupo
(
    id_grupo integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    data_criacao timestamp without time zone DEFAULT now(),
    observacao character varying(100) COLLATE pg_catalog."default",
    semestre character varying(6) COLLATE pg_catalog."default" NOT NULL,
    ativo boolean NOT NULL,
    CONSTRAINT grupo_pkey PRIMARY KEY (id_grupo)
);

CREATE TABLE IF NOT EXISTS public.instituicao
(
    cod_mec integer NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT instituicao_pkey PRIMARY KEY (cod_mec)
);

CREATE TABLE IF NOT EXISTS public.intervencao
(
    id_intervencao integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_usuario integer NOT NULL,
    id_estudante integer NOT NULL,
    data_intervencao timestamp without time zone NOT NULL,
    semestre character varying(6) COLLATE pg_catalog."default" NOT NULL,
    forma character varying(50) COLLATE pg_catalog."default" NOT NULL,
    formato text COLLATE pg_catalog."default",
    interacao text COLLATE pg_catalog."default",
    assunto character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT intervencao_pkey PRIMARY KEY (id_intervencao)
);

CREATE TABLE IF NOT EXISTS public.perfil
(
    id_perfil integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_usuario integer,
    id_curso integer,
    id_permissao integer,
    CONSTRAINT perfil_pkey PRIMARY KEY (id_perfil)
);

CREATE TABLE IF NOT EXISTS public.permissoes_usuario
(
    id_permissao integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cargo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    super_usuario boolean,
    deletar_intervencao boolean,
    editar_intervencao boolean,
    criar_intervencao boolean,
    criar_grupo boolean,
    editar_grupo boolean,
    deletar_grupo boolean,
    criar_aluno boolean,
    visualizar_aluno boolean,
    visualizar_risco boolean,
    CONSTRAINT permissoes_usuario_pkey PRIMARY KEY (id_permissao)
);

CREATE TABLE IF NOT EXISTS public.turma
(
    id_turma integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_disciplina integer,
    CONSTRAINT turma_pkey PRIMARY KEY (id_turma)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ultimo_acesso timestamp without time zone,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.curso
    ADD CONSTRAINT curso_id_instituicao_fkey FOREIGN KEY (id_instituicao)
    REFERENCES public.instituicao (cod_mec) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.disciplina
    ADD CONSTRAINT disciplina_id_curso_fkey FOREIGN KEY (id_curso)
    REFERENCES public.curso (id_curso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estatisticas_desempenho
    ADD CONSTRAINT estatisticas_desempenho_id_estudante_fkey FOREIGN KEY (id_estudante)
    REFERENCES public.estudante (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudante
    ADD CONSTRAINT estudante_id_instituicao_fkey FOREIGN KEY (id_instituicao)
    REFERENCES public.instituicao (cod_mec) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudante_grupo
    ADD CONSTRAINT aluno_grupo_id_estudante_fkey FOREIGN KEY (id_estudante)
    REFERENCES public.estudante (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudante_grupo
    ADD CONSTRAINT aluno_grupo_id_grupo_fkey FOREIGN KEY (id_grupo)
    REFERENCES public.grupo (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudante_turma
    ADD CONSTRAINT aluno_turma_id_estudante_fkey FOREIGN KEY (id_estudante)
    REFERENCES public.estudante (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estudante_turma
    ADD CONSTRAINT aluno_turma_id_turma_fkey FOREIGN KEY (id_turma)
    REFERENCES public.turma (id_turma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.intervencao
    ADD CONSTRAINT intervencao_id_estudante_fkey FOREIGN KEY (id_estudante)
    REFERENCES public.estudante (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.intervencao
    ADD CONSTRAINT intervencao_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perfil
    ADD CONSTRAINT perfil_id_curso_fkey FOREIGN KEY (id_curso)
    REFERENCES public.curso (id_curso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perfil
    ADD CONSTRAINT perfil_id_permissao_fkey FOREIGN KEY (id_permissao)
    REFERENCES public.permissoes_usuario (id_permissao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perfil
    ADD CONSTRAINT perfil_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.turma
    ADD CONSTRAINT turma_id_disciplina_fkey FOREIGN KEY (id_disciplina)
    REFERENCES public.disciplina (id_disciplina) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
